name: ludo-rl
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - pygame=2.6.1
  - python=3.12.7
  - pytorch=2.3.0
  - tensorboard=2.17.0
  - pip:
      - gymnasium==0.29.1
      - stable-baselines3==2.3.2
